---
title: "Using Git with RStudio"
output:
  github_document: default
---

Many people and groups use Git and [GitHub](https://github.com/) as a way to rigorously document changes in code. The layers of checks and balances are what makes git great but also incredibly overwhelming for a beginner. Here's how I started using git via RStudio:

## Layer 1: commit-pull-push

#### Starting glossary
* repo = repository
* git = versioning system that you can interact with through the command line or RStudio
* GitHub = online versioning website based on git
* commit = to save your changes to the version record
* push = to push your changes (commits) to your online Github account
* pull = to pull in your online Github repo to your local git folder; keeps your work up-to-date

#### Set-up
To start out, it's easiest work with just yourself or with one other person.  All your communication, then, is just between your local repository and the repository on github.com.  

[set-up process]

Now when you work in your git-tracked project in RStudio, you have the option of interacting with git in the git panel on the top right.  To commit, or save, a change, check the *Staged* box on the left side of the file(s) you want to commit, and then click the "Commit" button at the top. A window will pop up for you to write your commit message (i.e. "fixed typo" or "wrote a function for summing three numbers").  Once you submitted, you've committed these changes to your files locally, and you're almost ready to move them to the internet!

But before you *push* the files, you want to *pull* (down arrow) your github repository.  This helps you make sure that your updates will be applied to the most current version of your github repository.  If you're all up to date (more on if you're not later), then just push your commits straight through to github!  When you check your repository, you should see your commit displayed across the top of your repository. 

And that it's it!  Just use *commit-pull-push* (or just pull all the time like I do to make sure you're always up to date), and you'll have a clean, clear record of the changes you've made to your code over time.

## Layer 2: working with forks
If you're working on a slightly bigger project, you may want to add an additional layer of protection against unwanted changes.  By *forking* a repository, you create your own version of the repository that you can interact with as in the previous section.	

In order to interact with the original repository, you can *submit pull-requests* to add your new changes.  If other changes have been made to the original repository since you last interacted with it, you may have to *merge* your changes into the newest version or *rebase* your repository before adding in your new commits.



# TODO
*add info about how to use private email (and what to do if you already have some commits) https://stackoverflow.com/questions/3042437/change-commit-author-at-one-specific-commit note: spell amend correctly!




